# Use an official Node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Set environment variable to skip Cypress binary download
ENV CYPRESS_INSTALL_BINARY=0

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .


# Make port 5173 available to the world outside this container
EXPOSE 5173

# Run the app when the container launches
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
