# ============================================
# DATABASE CREDENTIALS SECRET
# ============================================
# Contains MySQL root password, database name, user, and password
# NOTE: In production, use proper secret management (Sealed Secrets, External Secrets Operator, etc.)
# 
# To update values:
# echo -n 'your-value' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: superproject-ns
  labels:
    app: apartment-system
    component: database
type: Opaque
data:
  # Default values (base64 encoded):
  # root-password: "secure_root_password_change_me"
  # database: "apartment_db"
  # username: "apartment"
  # password: "secure_password_change_me"
  root-password: c2VjdXJlX3Jvb3RfcGFzc3dvcmRfY2hhbmdlX21l
  database: YXBhcnRtZW50X2Ri
  username: YXBhcnRtZW50
  password: c2VjdXJlX3Bhc3N3b3JkX2NoYW5nZV9tZQ==
